version: '3.8'
services:
  app:
    build: .
    container_name: alquilarte-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/alquilarte
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/ping"]
      interval: 30s
      timeout: 3s
      retries: 3

  mongo:
    image: mongo:6
    container_name: alquilarte-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  prom:
    image: prom/prometheus:latest
    container_name: alquilarte-prom
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: alquilarte-grafana
    ports:
      - "3001:3000"
