global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'alquilarte-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['alquilarte-app:3000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
