name: CD - Deploy to Render

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Trigger Render Deploy
        run: |
          echo "🔹 Iniciando despliegue automático en Render..."
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
          echo "✅ Despliegue automático enviado correctamente."
